# Generated by Django 6.0 on 2026-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero_stat_delete_contactinfo_delete_homepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_text', models.TextField()),
                ('copyright_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='bg_class',
            field=models.CharField(choices=[('bg-orange', 'Orange'), ('bg-green', 'Green'), ('bg-blue', 'Blue'), ('bg-pink', 'Pink'), ('bg-red', 'Red'), ('bg-purple', 'Purple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='gradient',
            field=models.CharField(choices=[('gradient-pink', 'Pink'), ('gradient-blue', 'Blue'), ('gradient-orange', 'Orange'), ('gradient-green', 'Green')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(max_length=150),
        ),
    ]
