# Generated by Django 6.0 on 2026-01-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_contactinfo_footer_alter_feature_bg_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='card_description',
            field=models.TextField(default='card_description'),
        ),
        migrations.AddField(
            model_name='service',
            name='card_title',
            field=models.TextField(default='card_description'),
        ),
    ]
