# Generated by Django 6.0 on 2026-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AlterField(
            model_name='service',
            name='card_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='card_title',
            field=models.CharField(max_length=100),
        ),
    ]
