# Generated by Django 6.0 on 2026-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_service_description_remove_service_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True)),
            ],
        ),
    ]
