# Generated by Django 6.0 on 2026-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faqsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
            ],
        ),
    ]
