# Generated by Django 6.0 on 2026-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testimonialsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
