# Generated by Django 6.0 on 2026-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_brand_text_footer_brand_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.TextField(help_text='Format: Label|Number|Icon, ...')),
            ],
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='about',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='company_1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='company_2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='company_3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='company_4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='connect_1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='connect_2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='connect_3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='connect_4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='service_1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='service_2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='service_3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='service_4',
        ),
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(default='', help_text='Use line breaks for paragraphs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqsection',
            name='faqs',
            field=models.TextField(default='', help_text='Format: Question|Answer, ...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuresection',
            name='features',
            field=models.TextField(default='', help_text='Format: Title|Description|Icon|BgClass, ...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='company',
            field=models.TextField(default='', help_text='Comma-separated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='connect',
            field=models.TextField(default='', help_text='Comma-separated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='services',
            field=models.TextField(default='', help_text='Comma-separated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesection',
            name='services',
            field=models.TextField(default='', help_text='Format: Title|Description|Icon|Gradient, ...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonialsection',
            name='testimonials',
            field=models.TextField(default='', help_text='Format: Name|Role|Message|Rating, ...'),
            preserve_default=False,
        ),
    ]
