# Generated by Django 6.0 on 2026-01-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_statsection_delete_faq_delete_feature_delete_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='features/')),
                ('bg_class', models.CharField(choices=[('bg-orange', 'Orange'), ('bg-green', 'Green'), ('bg-blue', 'Blue'), ('bg-pink', 'Pink'), ('bg-red', 'Red'), ('bg-purple', 'Purple')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('icon', models.ImageField(upload_to='services/')),
                ('gradient', models.CharField(choices=[('gradient-pink', 'Pink'), ('gradient-blue', 'Blue'), ('gradient-orange', 'Orange'), ('gradient-green', 'Green')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='stats/')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='StatSection',
        ),
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='faqsection',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='featuresection',
            name='features',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='connect',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='services',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='services',
        ),
        migrations.RemoveField(
            model_name='testimonialsection',
            name='testimonials',
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='company_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='company_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='company_3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='company_4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='connect_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='connect_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='connect_3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='connect_4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='service_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='service_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='service_3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='service_4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
