# Generated by Django 6.0 on 2026-01-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_faq_feature_service_stat_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=100)),
                ('subtitle', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('phone_note', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('email_note', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
